dist: trusty
language: ruby
sudo: true
cache:
  bundler: true
  directories:
  - node_modules
services:
  - postgresql
  - docker

env:
  global:
    - APP_API_URL=https://gsd-api.cloudapps.digital
    - APP_API_USERNAME=performance123
    - PAAS_USER=gsd-deploy@digital.cabinet-office.gov.uk
    - PAAS_SERVICE=gsd-publish-data
    - DOCKER_USER=gsddeploy
    - DOCKER_REPOSITORY=gsddeploy
    - DOCKER_IMAGE=gsd-publish-data
    - DOCKER_FILE=etc/gsd-publish-data.df
    # APP_SECRET_KEY_BASE_STAGING
    - secure: "lJi634EBPWyOzjuroXhdb7/RsjpBg4/pZlw5KWmfFf0OLwLD1Mk6TS+LTVaSufRKiW5/mtFILIhGUFt+k6/WGVi30ZHX16WH2BsTtyBI724xeBZSeoRTauUlvuN3jx0MlQpl9QyxfCQtyNrK+gZbzSXT0GGryOJ7xLziQQy5AS8GMPQNEtDzoAJ91tEFH5Jn0+HmzU41Xw6ncSiElXyL+W4Zc4tu6WETvM+LU/LuHt5mHBXpMwJMUPka6xHSAwQSUXuvy4lWlyJXf8a8AptrG2I+uU00rW7jcwG7NUGl3njJfeNx7FdEKnz+dbiGEhzZL/rb/9YTs4qRyWUc/zJQR4SDEh8EsSAgtDieqwtPQVjGPNaazVafqSmE5tN6PLHuXcbXHEpD/7+3MHF1rZXiq8Ls+UMKxBcWDlFk7g+wZ0Ah+EmhSdFbmMYzxgvwXIjfyxQUisbXbW8cpWICEG7Wz2gnYndA9LGbLidQTObpi6/6dRjL3npP2Pu+05bMl4ZkG54WMJsAGZPZ/6RCPeDdM3MNxzvPSzDI+tjhEwkwXkIRQxP2KffHjG51AQdf1n14b8uVPnK8liV2d6fBojskekqeQiLaOQroT4vmzhZNQaoPCVFlaMqlY+FE+Yu6qKZJNHMbfye/dPxB3YNQ78yXtO9ftQRojd/gLiPjrVdOSgM="
    # APP_SECRET_KEY_BASE_PRODUCTION
    - secure: "BH89KWa3URZUAL8/7fMYoXdcy+3Wz51mVOwYK3XBTqlP9UU8CwS/1Z4aIJftdMJjsBXpEl789Jmj+HXjR7DDfCWqhjXwjyfLn8OWJtHXOr+IfjV7r7lb1cFf+DhdSN0fGuFRD3c8/+7gIiK1ODlNuSOaSAxaZnTR3NzMJqGq2k1EywJFe8kr79/f0TL+WQK1SrCs+yNZuIx3Zj4+hFLpv4QnNkdcRRsLS82WMnZq0p1mVMyuTG9XYqIDSc5KK8Hb2VuAtQrzvpyPNIIaV23+tHTpZGm3X4xrSX1xeRX70d+0/pFPKT8RKkLAvMTGHZn2NZ15RT/C3P1vcSVWS7kaIQVVxDuc9rMZzaLYqJUijiQAN+dALL6vQwFNe8gWpCRSYbSa4Q5SQ9+OiQ9sUr0pu/GY8/o6oxH3TnyVT8KXnlAg9jzjof4VZo/PDAnZNSGPvRXgpUHoa84T8B1lt9FhonwrCp0bWtH23XXjFmTbjAuPAZlyZG+FTAFcw76H5IckaFE+FPI48rgrZTEUZ1LoI3lZjWWvEDuzjAa/lr12DuM3g2bmFflVxn5eZ22AfV9TEMN4CiRrGVbngCynLl8KdUUtK9bssylparxAwZABO7bh4X8W9Z6osqFpE4MQfxj1BQeR5qy60xCKEAnPMTAV1gsBPLwDg/lytJyALtxo0ys="
    # APP_API_PASSWORD
    - secure: "TBTQbYoqPcELX6PJHtbxNDiydn+nlTY7eP8Y6XbnXFD/n369K3MhTb9/K/3kSjtLnqrk0W7AqON0KC6a7IBpqm+fLR4A8Yb44tTLWEMCv8RUpd5BxIulc9XzX4+RknY9gLIWRha0skTuPwybjOGMOXlHX95BjG727+AkLdd1iTAjuIGjZek6lSXcw5ONg2Gec+10lZ/olJMwCzWXj154EaPbDX1cQzkhmxaEMz4q0UUFaVq6F2ys0GEnglCOk/NDRPyb9OtSZ2JqMA6GEwChviK82lshFuTuVJOojfT7heM0B8d5VrhAtKk5j7ZXLlzFUVxgX6mMpy1lc/pOZgkeeyRf0mcizc9bIGGrwvfy29eQqiFvSlg9pvhWIhrgfQKJEYTYtsH06rP4hTBNayeVAdLeS4HZcr2Ex58gVimOtyVtOzADusazZBXOjEuTBSQdhGJ/0oJ2OWYtWGz/ZeHra15/go1iaOX/kWpY1nVHPQeRQ0WB2IJY4TA3kbAj+W6igOGeWOfS3Pfh35SOwBL017mr8/2HOPlSLyZBlUXz/QWiobW0JzRF6BShWae13PlDRSDRfdlOV8Ogk2SYwrZ80Kc0/GYUwVvUnL89iltrtnrIDURHAjcDqbGHzxnLiWFDydN+NO9/OzI0vsYN1TuN2k33plRz5pFKnebV28vbQpY="
    # PAAS_PASSWORD
    - secure: "OhZDhNPpKILFFPhqbwTEdTYDPG6OuTrY6AunGzBw9o/l9egdeUyOf78B6GiCnir2IBDfmFbsj1H9UklSyimUxdW60v42Ta3E75bOBymzrvMPO5gUBCV7rwK2HHHrIXsU6rIFA3scpMdaUm4OB6pfdr9s7MuwjsoAT4qlv7oYs9dCnvUu4ZovI8eKQWQ7jOoeC0oRTtO8K4cJx9Nrvt2/Sm5lgnjxbnHKyt+DAiLHc/t5fNJF7+D+WCjGy9BPb703caj/mM/DeekB3v7bag5SPt60IeFJuc8y31F0qBbuzRgSnlIseGNdN5EhIU8NaMN54LHjOx2KoU/FK6PQzpmaf8Wi19YZTiwEl6vCm3JYB5VMJlwwD41TneUFg9IkhxYAM4KB4CdcQIH9xWOLt23RHxxzly7P7quHzgLaIXOcGRH9MzVD+J0lgzw7mtOLa2rlnp0Y0V4gIW7ivdh9CXM4nUjAH3OdX7jks7Jldwm19fNFwz3yPKxYuFWqekwFU7Zmbh8cEbsvaQbUfvlXx+Fhm3835DXiEb29bTPkMqgqozHYMCEm6RhqLVoN+1G0pgWmWHgDBDpJkwYl6Gg5vfqt6ggr6muwUkUeC9gebBxCan09r4IKMKOvTROeFlS/4NMa3Oxc/niUpD219tVi3iuHWQZZ5FbY+1IBIAX/x9rq0tE="
    # DOCKER_PASSWORD for user gsddeploy
    - secure: "iPXGmF95XjH0A1iB8KuB0QnSHRm4U2zdyGomy1tB3553zawL4XdgqFsqRqT1VKhVBpwi7nT6UkEjQevcSmraWwW3vf8T2zCUTYTXIL5HbD4UXBgweZDHwUTU7v7ZSjjKruJuhKlVNS1LxlglDxbZJsGHvzPF1NQQcXYcjHrRd6sJfJI9lc9yyWzV3+AwzVd88OSMkEHImb+K/A5Vl2zZE5Hvf0R7tWOXuo59O3C1CfcjQINAodFcRlOhj7bvlkd2bwN8aWeoC3Yb5+8FLRylnlDpANTmG0GE+eSqp+Exqp+BuaqnQv3Iv6jipC2ET0hb+fgN4YWd4NQL1jBrwxlq5iFC5FLeH5I7alg1N1wTE5e03iUo/2C+MlRoztYLjKHD0+NUQSdj+xeLh87p4SJl6Gefujraek1Yz2tu0E/lBGacjRpAL89mABS//dnqRUmr90Zyl0y1FUZhWNs0siDi7RqeaU2JmLP2N4JdyAIV4Kq9VWyPXzxhuOzMa47PVtQi9ySW3/K/Wm6EMxbkz4+b6MzRzD+9RPWV/qaMSs21rLfnLY8/9PQjmraMsaSJ14OHRQi2ogZYC80L1Vo2HQeWSTA4lYtKpIhvmrwNMdZu9Met3ynG/FkUQhJxGhiFYRbmx9QVVi5Z5cgchilp3pg2lyTc+FNEtDYamg7G0RWGCtI="

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp .env.example .env
  - npm install
  - bundle --without development production
  - bundle exec rake assets:precompile
  - cp config/database.yml.travis config/database.yml

script:
  - bundle exec govuk-lint-ruby app lib spec
  - xvfb-run -a bundle exec rspec

deploy:
 - provider: script
   script: APP_SECRET_KEY_BASE=$APP_SECRET_KEY_BASE_STAGING etc/deploy.sh staging
   skip_cleanup: true
   on:
     branch: staging
 - provider: script
   script: APP_SECRET_KEY_BASE=$APP_SECRET_KEY_BASE_PRODUCTION etc/deploy.sh production
   skip_cleanup: true
   on:
     branch: production

